name: kheper
channels:
- conda-forge
dependencies:
- conda-forge::pandas=0.24.2
- conda-forge::scikit-learn=0.21.2
- conda-forge::jupyter=1.0.0
- conda-forge::ipykernel=5.1.1
- conda-forge::nb_conda_kernels=2.2.2
- conda-forge::pyyaml=5.1.1
